### ISSUE TITLE
How to train and test?

### ISSUE THREAD

**Issue by jinzhenmu** [shawLyu/HR-Depth#1]
nice job.

-how to train  and test?   the codes no contain this step

**Comment by shawLyu** [comment]
1. We have uploaded a simple script for testing single image, [test_single_image.ipynb](https://github.com/shawLyu/HR-Depth/blob/main/test_single_image.ipynb).
2. Our main contributions are mainly about depth network, which had been released. The training parts are modified according to [Monodepth2](https://github.com/nianticlabs/monodepth2), and we will release them in the future. If you want to train right now, you can try to change original network in Monodepth2 to ours.

**Comment by jinzhenmu** [comment]
thanks a lot.
