### ISSUE TITLE
About your network architecture

### ISSUE THREAD

**Issue by FangGet** [shawLyu/HR-Depth#2]
Hi, Xiaoyang,
    First thanks for open-sourcing this project, great job.
    There is something inconsistent between the code and your paper about the network architecture. After digging into the code, I think the ar should be like this:
![image](https://user-images.githubusercontent.com/11433213/103330815-186cbe00-4a9e-11eb-884f-c8f7a788327b.png)
    which is not corresponding to your paper.

**Comment by shawLyu** [comment]
Hi, Fang,
Thanks for following our work. Can you tell me in detail which node has problem? Because I did not know specific problems between figure you provided and ours. Maybe we have different representations for the same architecture. Welcome to discuss! Thank you!

**Comment by FangGet** [comment]
From my point of view, the node [40] from my picture corresponding to X_5^e from the paper, so how to generate the X_5^d from X_5^e from your paper? for my picture, I see [40] is fused into 31 with directly upsampling.

**Comment by FangGet** [comment]
or your  X_5^e is exactly the same as X_5^d, without any operation? just for expression convenience?

**Comment by shawLyu** [comment]
I'm sorry for ambiguity. In our paper, we used a red arrow to connect $X_5^e$ with $X_5^e$ which means convolution with $3 \times 3$ kernel. In the code, `self.convs["X_40_Conv_0"]` represented for this operation. $X^5_e$ represented for features extracted from encoder corresponding to `input_features[5]` in the code and $X^5_d$ is the intermediate variable in `nestConv` function. You can check the code again and I hope this answer can solve your problem.

**Comment by FangGet** [comment]
ok, I will check for that, thanks for explanation.
