### ISSUE TITLE
Training Details?

### ISSUE THREAD

**Issue by chenerg** [shawLyu/HR-Depth#3]
`The training parts are modified according to Monodepth2`, so what changes have you done during training.

**Comment by shawLyu** [comment]
Thanks for being interested in our work. 
1. For HR-Depth result ( using Resnet-18 as encoder ), you can simply change the `depth_decoder` to `HRDepthDecoder` ( the key of our output directory is `outputs[("disparity", "Scale{}".format(scale))]` ).
2. For Lite-HR-Depth ( using MobileNetV3 as encoder ), you can reinplement it according to the training details in the paper. We did not use any tricks not mentioned in the paper.

Our training codes will be released soon. Hope this answer can help you. If you encounter other problems, welcome to discuss.
