### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by hyBlue** [shawLyu/HR-Depth#6]
Hi, you're work is really inspiring.

Can you share the weight of the model trained with KITTI (M), 192x640?

**Comment by shawLyu** [comment]
I have uploaded the model. You can download it from  [HR_Depth_K_M_640x192](http://hr-depth-pretrain-model.s3.amazonaws.com/HR_Depth_K_M_640x192.zip)

**Comment by hyBlue** [comment]
Thanks for sharing!
